[package]
name = "gotp"
version = "0.1.2"
edition = "2024"
authors = ["Gergely Brautigam <skarlso777@gmail.com>"]
description = "Generate totp codes for various accounts which are saved and AES encrypted."
documentation = "https://github.com/Skarlso/totp/blob/master/README.md"
homepage = "https://github.com/Skarlso/totp"
repository = "https://github.com/Skarlso/totp"
readme = "README.md"
keywords = ["totp", "otp", "aes", "account"]
categories = ["command-line-interface"]
license-file = "LICENSE"
[badges]
travis-ci = { repository = "Skarlso/totp", branch = "master" }
is-it-maintained-issue-resolution = { repository = "Skarlso/totp" }
is-it-maintained-open-issues = { repository = "Skarlso/totp" }
maintenance = { status = "actively-developed" }

[dependencies]
clap = {version = "4.6.1"}
chrono = "0.4.44"
data-encoding = "2.11.0"
byteorder = "1.5.0"
openssl = "0.10.80"
hex = "0.4.3"
rpassword = "7.5.4"

